export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_FAILURE = 'FETCH_SONGS_FAILURE';

export const CREATE_SONG_REQUEST = 'CREATE_SONG_REQUEST';
export const CREATE_SONG_SUCCESS = 'CREATE_SONG_SUCCESS';
export const CREATE_SONG_FAILURE = 'CREATE_SONG_FAILURE';

export const UPDATE_SONG_REQUEST = 'UPDATE_SONG_REQUEST';
export const UPDATE_SONG_SUCCESS = 'UPDATE_SONG_SUCCESS';
export const UPDATE_SONG_FAILURE = 'UPDATE_SONG_FAILURE';

export const DELETE_SONG_REQUEST = 'DELETE_SONG_REQUEST';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAILURE = 'DELETE_SONG_FAILURE';